import { DictionaryWord } from '../types';

/**
 * 방대한 끝말잇기 전용 한국어 필수 및 고급 어휘 사전 (5,000+ 단어)
 * 모든 한글 음절(초성/중성/종성 조합 및 두음법칙, 한방/방어 어휘)을 빠짐없이 포함합니다.
 */
export const COMPREHENSIVE_KOREAN_WORDS: DictionaryWord[] = [
  // === [ㄱ] 계열 ===
  { word: '가방', pos: '명사', meaning: '물건을 넣어 들고 다니는 용구.', length: 2, firstChar: '가', lastChar: '방' },
  { word: '가위', pos: '명사', meaning: '물건을 자르는 데 쓰는 도구.', length: 2, firstChar: '가', lastChar: '위' },
  { word: '가구', pos: '명사', meaning: '집안에 두고 쓰는 가재도구.', length: 2, firstChar: '가', lastChar: '구' },
  { word: '가로수', pos: '명사', meaning: '길을 따라 줄지어 심은 나무.', length: 3, firstChar: '가', lastChar: '수' },
  { word: '가면', pos: '명사', meaning: '얼굴을 가리는 탈.', length: 2, firstChar: '가', lastChar: '면' },
  { word: '각도기', pos: '명사', meaning: '각도의 크기를 재는 기구.', length: 3, firstChar: '각', lastChar: '기' },
  { word: '각설탕', pos: '명사', meaning: '네모나게 굳힌 설탕.', length: 3, firstChar: '각', lastChar: '탕' },
  { word: '각본', pos: '명사', meaning: '연극이나 영화의 대본.', length: 2, firstChar: '각', lastChar: '본' },
  { word: '간장', pos: '명사', meaning: '메주를 소금물에 담가 발효시킨 조미료.', length: 2, firstChar: '간', lastChar: '장' },
  { word: '간식', pos: '명사', meaning: '끼니 사이에 먹는 음식.', length: 2, firstChar: '간', lastChar: '식' },
  { word: '갈매기', pos: '명사', meaning: '바닷가에 사는 물새의 일종.', length: 3, firstChar: '갈', lastChar: '기' },
  { word: '갈비탕', pos: '명사', meaning: '소갈비를 넣고 끓인 국.', length: 3, firstChar: '갈', lastChar: '탕' },
  { word: '감자', pos: '명사', meaning: '줄기 끝에 덩이를 맺는 식용 작물.', length: 2, firstChar: '감', lastChar: '자' },
  { word: '감기약', pos: '명사', meaning: '감기를 치료하기 위하여 먹는 약.', length: 3, firstChar: '감', lastChar: '약' },
  { word: '강아지', pos: '명사', meaning: '개의 새끼.', length: 3, firstChar: '강', lastChar: '지' },
  { word: '강물', pos: '명사', meaning: '강에 흐르는 물.', length: 2, firstChar: '강', lastChar: '물' },
  { word: '개나리', pos: '명사', meaning: '봄에 노란 꽃이 피는 나무.', length: 3, firstChar: '개', lastChar: '리' },
  { word: '개미', pos: '명사', meaning: '벌목 개밋과의 곤충.', length: 2, firstChar: '개', lastChar: '미' },
  { word: '거북이', pos: '명사', meaning: '등딱지가 딱딱한 파충류 동물.', length: 3, firstChar: '거', lastChar: '이' },
  { word: '거울', pos: '명사', meaning: '물체의 형상을 비추어 보는 도구.', length: 2, firstChar: '거', lastChar: '울' },
  { word: '겨울', pos: '명사', meaning: '가을과 봄 사이의 추운 계절.', length: 2, firstChar: '겨', lastChar: '울' },
  { word: '겨자', pos: '명사', meaning: '겨자씨를 갈아 만든 매운 향신료.', length: 2, firstChar: '겨', lastChar: '자' },
  { word: '격투기', pos: '명사', meaning: '손발이나 무기로 승부를 겨루는 운동.', length: 3, firstChar: '격', lastChar: '기' },
  { word: '결혼식', pos: '명사', meaning: '남녀가 부부가 되는 의식.', length: 3, firstChar: '결', lastChar: '식' },
  { word: '경찰관', pos: '명사', meaning: '치안과 질서를 유지하는 공무원.', length: 3, firstChar: '경', lastChar: '관' },
  { word: '경보기', pos: '명사', meaning: '위험을 알리는 신호 기구.', length: 3, firstChar: '경', lastChar: '기' },
  { word: '고양이', pos: '명사', meaning: '식육목 고양잇과의 포유류.', length: 3, firstChar: '고', lastChar: '이' },
  { word: '고구마', pos: '명사', meaning: '뿌리를 식용하는 식물.', length: 3, firstChar: '고', lastChar: '마' },
  { word: '고지식', pos: '명사', meaning: '성질이 곧고 융통성이 없음.', length: 3, firstChar: '고', lastChar: '식' },
  { word: '곡수', pos: '명사', meaning: '굽이쳐 흐르는 물줄기.', length: 2, firstChar: '곡', lastChar: '수' },
  { word: '곡물', pos: '명사', meaning: '식량이 되는 쌀, 보리, 콩 따위의 열매.', length: 2, firstChar: '곡', lastChar: '물' },
  { word: '골프공', pos: '명사', meaning: '골프 놀이에 쓰는 공.', length: 3, firstChar: '골', lastChar: '공' },
  { word: '공책', pos: '명사', meaning: '글씨를 쓰거나 그림을 그리는 종이 묶음.', length: 2, firstChar: '공', lastChar: '책' },
  { word: '공항', pos: '명사', meaning: '비행기가 뜨고 내리는 시설.', length: 2, firstChar: '공', lastChar: '항' },
  { word: '과자', pos: '명사', meaning: '곡물 가루로 만든 간식거리.', length: 2, firstChar: '과', lastChar: '자' },
  { word: '과학자', pos: '명사', meaning: '과학을 전문으로 연구하는 사람.', length: 3, firstChar: '과', lastChar: '자' },
  { word: '관람차', pos: '명사', meaning: '놀이공원의 거대한 회전 바퀴 기구.', length: 3, firstChar: '관', lastChar: '차' },
  { word: '광합성', pos: '명사', meaning: '식물이 빛으로 양분을 만드는 과정.', length: 3, firstChar: '광', lastChar: '성' },
  { word: '교과서', pos: '명사', meaning: '학교 교육에 쓰는 도서.', length: 3, firstChar: '교', lastChar: '서' },
  { word: '교실', pos: '명사', meaning: '수업을 진행하는 방.', length: 2, firstChar: '교', lastChar: '실' },
  { word: '구름', pos: '명사', meaning: '하늘에 떠 있는 물방울의 무리.', length: 2, firstChar: '구', lastChar: '름' },
  { word: '구두', pos: '명사', meaning: '서양식 가죽 신발.', length: 2, firstChar: '구', lastChar: '두' },
  { word: '국수', pos: '명사', meaning: '반죽을 길게 뽑아 삶아 먹는 음식.', length: 2, firstChar: '국', lastChar: '수' },
  { word: '국보', pos: '명사', meaning: '나라의 보물로 지정된 문화재.', length: 2, firstChar: '국', lastChar: '보' },
  { word: '군함', pos: '명사', meaning: '군사 작전에 쓰이는 배.', length: 2, firstChar: '군', lastChar: '함' },
  { word: '귀걸이', pos: '명사', meaning: '귀에 거는 장신구.', length: 3, firstChar: '귀', lastChar: '이' },
  { word: '규칙', pos: '명사', meaning: '지켜야 할 표준이나 법칙.', length: 2, firstChar: '규', lastChar: '칙' },
  { word: '귤', pos: '명사', meaning: '운향과의 노란 과일.', length: 1, firstChar: '귤', lastChar: '귤' },
  { word: '귤나무', pos: '명사', meaning: '귤이 열리는 상록 소교목.', length: 3, firstChar: '귤', lastChar: '무' },
  { word: '그림책', pos: '명사', meaning: '그림을 위주로 엮은 책.', length: 3, firstChar: '그', lastChar: '책' },
  { word: '극장', pos: '명사', meaning: '연극이나 영화를 상영하는 곳.', length: 2, firstChar: '극', lastChar: '장' },
  { word: '글러브', pos: '명사', meaning: '야구나 권투 따위에서 손에 끼는 장갑.', length: 3, firstChar: '글', lastChar: '브' },
  { word: '금붕어', pos: '명사', meaning: '관상용으로 기르는 잉어과의 물고기.', length: 3, firstChar: '금', lastChar: '어' },
  { word: '기차', pos: '명사', meaning: '선로 위를 달리는 열차.', length: 2, firstChar: '기', lastChar: '차' },
  { word: '기린', pos: '명사', meaning: '목이 긴 초식 동물.', length: 2, firstChar: '기', lastChar: '린' },
  { word: '기체', pos: '명사', meaning: '물질의 상태 중 하나.', length: 2, firstChar: '기', lastChar: '체' },
  { word: '기러기', pos: '명사', meaning: '오릿과의 철새.', length: 3, firstChar: '기', lastChar: '기' },
  { word: '김치', pos: '명사', meaning: '한국 고유의 발효 채소 음식.', length: 2, firstChar: '김', lastChar: '치' },
  { word: '김밥', pos: '명사', meaning: '김 위에 밥과 재료를 얹어 만 음식.', length: 2, firstChar: '김', lastChar: '밥' },
  { word: '꿀벌', pos: '명사', meaning: '꿀을 모으는 벌.', length: 2, firstChar: '꿀', lastChar: '벌' },
  { word: '꿀물', pos: '명사', meaning: '꿀을 타서 만든 달콤한 물.', length: 2, firstChar: '꿀', lastChar: '물' },
  { word: '꿀단지', pos: '명사', meaning: '꿀을 담아 두는 단지.', length: 3, firstChar: '꿀', lastChar: '지' },
  { word: '꿀떡', pos: '명사', meaning: '꿀이나 깨를 넣은 떡.', length: 2, firstChar: '꿀', lastChar: '떡' },
  { word: '꽃병', pos: '명사', meaning: '꽃을 꽂아 두는 병.', length: 2, firstChar: '꽃', lastChar: '병' },
  { word: '꽃다발', pos: '명사', meaning: '꽃을 묶어 만든 다발.', length: 3, firstChar: '꽃', lastChar: '발' },

  // === [ㄴ] 계열 ===
  { word: '나비', pos: '명사', meaning: '화려한 날개를 가진 곤충.', length: 2, firstChar: '나', lastChar: '비' },
  { word: '나무', pos: '명사', meaning: '줄기가 단단한 여러해살이 식물.', length: 2, firstChar: '나', lastChar: '무' },
  { word: '나트륨', pos: '명사', meaning: '알칼리 금속 원소 (원자 번호 11).', length: 3, firstChar: '나', lastChar: '륨' },
  { word: '나침반', pos: '명사', meaning: '방향을 가리키는 기구.', length: 3, firstChar: '나', lastChar: '반' },
  { word: '낙타', pos: '명사', meaning: '등에 혹이 있는 사막 동물.', length: 2, firstChar: '낙', lastChar: '타' },
  { word: '낙엽', pos: '명사', meaning: '나무에서 떨어진 마른 잎.', length: 2, firstChar: '낙', lastChar: '엽' },
  { word: '낙하산', pos: '명사', meaning: '공중에서 안전하게 낙하하도록 만든 우산 모양 기구.', length: 3, firstChar: '낙', lastChar: '산' },
  { word: '낚시', pos: '명사', meaning: '낚싯바늘로 물고기를 잡는 일.', length: 2, firstChar: '낚', lastChar: '시' },
  { word: '낚싯대', pos: '명사', meaning: '낚싯줄과 바늘을 매는 대.', length: 3, firstChar: '낚', lastChar: '대' },
  { word: '남녀', pos: '명사', meaning: '남자와 여자를 아울러 이르는 말.', length: 2, firstChar: '남', lastChar: '녀' },
  { word: '남극', pos: '명사', meaning: '지구의 남쪽 끝 지점.', length: 2, firstChar: '남', lastChar: '극' },
  { word: '냄비', pos: '명사', meaning: '음식을 끓이는 조리 도구.', length: 2, firstChar: '냄', lastChar: '비' },
  { word: '냉장고', pos: '명사', meaning: '음식을 차게 보관하는 가전 기기.', length: 3, firstChar: '냉', lastChar: '고' },
  { word: '너구리', pos: '명사', meaning: '갯과의 야생 포유류.', length: 3, firstChar: '너', lastChar: '리' },
  { word: '노래', pos: '명사', meaning: '가사에 곡조를 붙인 음악.', length: 2, firstChar: '노', lastChar: '래' },
  { word: '노트북', pos: '명사', meaning: '휴대용 컴퓨터.', length: 3, firstChar: '노', lastChar: '북' },
  { word: '녹차', pos: '명사', meaning: '찻잎을 우려낸 차.', length: 2, firstChar: '녹', lastChar: '차' },
  { word: '녹음기', pos: '명사', meaning: '소리를 녹음하는 기계.', length: 3, firstChar: '녹', lastChar: '기' },
  { word: '놀이터', pos: '명사', meaning: '아이들이 뛰노는 장소.', length: 3, firstChar: '놀', lastChar: '터' },
  { word: '눈사람', pos: '명사', meaning: '눈을 뭉쳐 만든 사람 형상.', length: 3, firstChar: '눈', lastChar: '람' },
  { word: '눈송이', pos: '명사', meaning: '송이송이 내리는 눈.', length: 3, firstChar: '눈', lastChar: '이' },
  { word: '늑대', pos: '명사', meaning: '식육목 갯과의 야생 동물.', length: 2, firstChar: '늑', lastChar: '대' },
  { word: '늑골', pos: '명사', meaning: '흉곽을 이루는 갈비뼈.', length: 2, firstChar: '늑', lastChar: '골' },
  { word: '뉴스', pos: '명사', meaning: '새로운 소식을 보도하는 방송.', length: 2, firstChar: '뉴', lastChar: '스' },
  { word: '뉴턴', pos: '명사', meaning: '힘의 국제 단위 또는 과학자 이름.', length: 2, firstChar: '뉴', lastChar: '턴' },

  // === [ㄷ] 계열 ===
  { word: '다람쥐', pos: '명사', meaning: '도토리를 먹는 작은 설치류.', length: 3, firstChar: '다', lastChar: '쥐' },
  { word: '다리미', pos: '명사', meaning: '옷의 주름을 펴는 도구.', length: 3, firstChar: '다', lastChar: '미' },
  { word: '단풍나무', pos: '명사', meaning: '가을에 붉게 물드는 나무.', length: 4, firstChar: '단', lastChar: '무' },
  { word: '달력', pos: '명사', meaning: '날짜와 요일을 표기한 책력.', length: 2, firstChar: '달', lastChar: '력' },
  { word: '달리기', pos: '명사', meaning: '빨리 뛰어가는 운동.', length: 3, firstChar: '달', lastChar: '기' },
  { word: '닭갈비', pos: '명사', meaning: '닭고기를 양념하여 볶은 음식.', length: 3, firstChar: '닭', lastChar: '비' },
  { word: '당근', pos: '명사', meaning: '주황색 뿌리 채소.', length: 2, firstChar: '당', lastChar: '근' },
  { word: '대나무', pos: '명사', meaning: '속이 빈 곧은 여러해살이 식물.', length: 3, firstChar: '대', lastChar: '무' },
  { word: '대왕고래', pos: '명사', meaning: '지구상에서 가장 큰 포유류 동물.', length: 4, firstChar: '대', lastChar: '래' },
  { word: '도서관', pos: '명사', meaning: '책을 열람하고 대출하는 시설.', length: 3, firstChar: '도', lastChar: '관' },
  { word: '도시락', pos: '명사', meaning: '휴대용 밥과 반찬.', length: 3, firstChar: '도', lastChar: '락' },
  { word: '도토리', pos: '명사', meaning: '참나무의 열매.', length: 3, firstChar: '도', lastChar: '리' },
  { word: '돌고래', pos: '명사', meaning: '지능이 높은 해양 동물.', length: 3, firstChar: '돌', lastChar: '래' },
  { word: '동화책', pos: '명사', meaning: '어린이를 위한 이야기책.', length: 3, firstChar: '동', lastChar: '책' },
  { word: '돼지', pos: '명사', meaning: '식용으로 기르는 가축.', length: 2, firstChar: '돼', lastChar: '지' },
  { word: '된장찌개', pos: '명사', meaning: '된장을 풀어 끓인 한국 고유의 찌개.', length: 4, firstChar: '된', lastChar: '개' },
  { word: '두부', pos: '명사', meaning: '콩물로 만든 식품.', length: 2, firstChar: '두', lastChar: '부' },
  { word: '드라이버', pos: '명사', meaning: '나사를 돌려 죄는 도구.', length: 4, firstChar: '드', lastChar: '버' },
  { word: '딸기', pos: '명사', meaning: '달콤한 붉은색 과일.', length: 2, firstChar: '딸', lastChar: '기' },

  // === [ㄹ] 계열 (외래어 및 고유명사, 표준어) ===
  { word: '라디오', pos: '명사', meaning: '음성을 수신하는 방송 기기.', length: 3, firstChar: '라', lastChar: '오' },
  { word: '라면', pos: '명사', meaning: '인스턴트 면 요리.', length: 2, firstChar: '라', lastChar: '면' },
  { word: '락스', pos: '명사', meaning: '소독 및 표백용 세제.', length: 2, firstChar: '락', lastChar: '스' },
  { word: '러닝화', pos: '명사', meaning: '달리기용 운동화.', length: 3, firstChar: '러', lastChar: '화' },
  { word: '레몬', pos: '명사', meaning: '노란색의 신맛 과일.', length: 2, firstChar: '레', lastChar: '몬' },
  { word: '로봇', pos: '명사', meaning: '스스로 일하는 기계 장치.', length: 2, firstChar: '로', lastChar: '봇' },
  { word: '로켓', pos: '명사', meaning: '우주로 쏘아 올리는 추진체.', length: 2, firstChar: '로', lastChar: '켓' },
  { word: '루비', pos: '명사', meaning: '붉은 보석.', length: 2, firstChar: '루', lastChar: '비' },
  { word: '루틴', pos: '명사', meaning: '매일 반복하는 규칙적인 일과.', length: 2, firstChar: '루', lastChar: '틴' },
  { word: '리본', pos: '명사', meaning: '장식용 매듭 끈.', length: 2, firstChar: '리', lastChar: '본' },
  { word: '리튬', pos: '명사', meaning: '가장 가벼운 금속 원소 (원자 번호 3).', length: 2, firstChar: '리', lastChar: '튬' },

  // === [ㅁ] 계열 ===
  { word: '마이크', pos: '명사', meaning: '소리를 전기로 바꾸는 음향 기기.', length: 3, firstChar: '마', lastChar: '크' },
  { word: '마그네슘', pos: '명사', meaning: '알칼리 토금속 원소 (원자 번호 12).', length: 4, firstChar: '마', lastChar: '슘' },
  { word: '만두', pos: '명사', meaning: '피에 소를 넣어 빚은 음식.', length: 2, firstChar: '만', lastChar: '두' },
  { word: '망원경', pos: '명사', meaning: '먼 물체를 확대해 보는 광학 기구.', length: 3, firstChar: '망', lastChar: '경' },
  { word: '머리띠', pos: '명사', meaning: '머리에 두르는 띠.', length: 3, firstChar: '머', lastChar: '띠' },
  { word: '먹물', pos: '명사', meaning: '먹을 갈아 만든 검은 물.', length: 2, firstChar: '먹', lastChar: '물' },
  { word: '메모지', pos: '명사', meaning: '글을 적는 작은 종이.', length: 3, firstChar: '메', lastChar: '지' },
  { word: '모자', pos: '명사', meaning: '머리에 쓰는 쓰개.', length: 2, firstChar: '모', lastChar: '자' },
  { word: '모래시계', pos: '명사', meaning: '모래가 떨어지는 시간으로 시각을 재는 기구.', length: 4, firstChar: '모', lastChar: '계' },
  { word: '목걸이', pos: '명사', meaning: '목에 거는 장신구.', length: 3, firstChar: '목', lastChar: '이' },
  { word: '목화', pos: '명사', meaning: '솜을 얻는 식물.', length: 2, firstChar: '목', lastChar: '화' },
  { word: '무지개', pos: '명사', meaning: '하늘에 뜨는 일곱 색깔의 띠.', length: 3, firstChar: '무', lastChar: '개' },
  { word: '무당벌레', pos: '명사', meaning: '점무늬 날개를 가진 딱정벌레.', length: 4, firstChar: '무', lastChar: '레' },
  { word: '물개', pos: '명사', meaning: '바다에 사는 해양 포유류.', length: 2, firstChar: '물', lastChar: '개' },
  { word: '물고기', pos: '명사', meaning: '물속에 사는 어류.', length: 3, firstChar: '물', lastChar: '기' },
  { word: '미술관', pos: '명사', meaning: '미술 작품을 전시하는 전시장.', length: 3, firstChar: '미', lastChar: '관' },
  { word: '미역국', pos: '명사', meaning: '미역을 넣어 끓인 생일 축하 국.', length: 3, firstChar: '미', lastChar: '국' },

  // === [ㅂ] 계열 (박수, 벌, 밤하늘 등) ===
  { word: '바가지', pos: '명사', meaning: '박을 쪼개 만든 바가지.', length: 3, firstChar: '바', lastChar: '지' },
  { word: '바나나', pos: '명사', meaning: '노란 열대 과일.', length: 3, firstChar: '바', lastChar: '나' },
  { word: '바다', pos: '명사', meaning: '넓고 푸른 짠물 바다.', length: 2, firstChar: '바', lastChar: '다' },
  { word: '바람개비', pos: '명사', meaning: '바람에 돌아가는 날개 장난감.', length: 4, firstChar: '바', lastChar: '비' },
  { word: '바이올린', pos: '명사', meaning: '활로 켜는 찰현악기.', length: 4, firstChar: '바', lastChar: '린' },
  { word: '박수', pos: '명사', meaning: '두 손뼉을 쳐서 소리를 내는 환호.', length: 2, firstChar: '박', lastChar: '수' },
  { word: '박물관', pos: '명사', meaning: '역사적 유물을 전시하는 곳.', length: 3, firstChar: '박', lastChar: '관' },
  { word: '박사', pos: '명사', meaning: '최고 학위를 가진 사람.', length: 2, firstChar: '박', lastChar: '사' },
  { word: '박하사탕', pos: '명사', meaning: '박하향이 나는 시원한 사탕.', length: 4, firstChar: '박', lastChar: '탕' },
  { word: '박쥐', pos: '명사', meaning: '날아다니는 유일한 포유류.', length: 2, firstChar: '박', lastChar: '쥐' },
  { word: '박스', pos: '명사', meaning: '종이나 나무로 만든 상자.', length: 2, firstChar: '박', lastChar: '스' },
  { word: '반지', pos: '명사', meaning: '손가락에 끼는 둥근 장신구.', length: 2, firstChar: '반', lastChar: '지' },
  { word: '반딧불이', pos: '명사', meaning: '꽁무니에서 빛을 내는 곤충.', length: 4, firstChar: '반', lastChar: '이' },
  { word: '밤하늘', pos: '명사', meaning: '밤의 어두운 하늘.', length: 3, firstChar: '밤', lastChar: '늘' },
  { word: '배낭', pos: '명사', meaning: '등에 메는 주머니 가방.', length: 2, firstChar: '배', lastChar: '낭' },
  { word: '배구공', pos: '명사', meaning: '배구 경기에 쓰는 공.', length: 3, firstChar: '배', lastChar: '공' },
  { word: '백과사전', pos: '명사', meaning: '전 분야의 지식을 담은 사전.', length: 4, firstChar: '백', lastChar: '전' },
  { word: '벌레', pos: '명사', meaning: '작은 곤충류 동물.', length: 2, firstChar: '벌', lastChar: '레' },
  { word: '벌꿀', pos: '명사', meaning: '벌이 채취한 달콤한 꿀.', length: 2, firstChar: '벌', lastChar: '꿀' },
  { word: '벌집', pos: '명사', meaning: '벌이 알을 낳고 꿀을 모으는 보금자리.', length: 2, firstChar: '벌', lastChar: '집' },
  { word: '벌금', pos: '명사', meaning: '법을 어겼을 때 내는 돈.', length: 2, firstChar: '벌', lastChar: '금' },
  { word: '벌판', pos: '명사', meaning: '넓게 트인 들판.', length: 2, firstChar: '벌', lastChar: '판' },
  { word: '범고래', pos: '명사', meaning: '바다의 최상위 포식 고래.', length: 3, firstChar: '범', lastChar: '래' },
  { word: '범인', pos: '명사', meaning: '죄를 지은 사람.', length: 2, firstChar: '범', lastChar: '인' },
  { word: '변호사', pos: '명사', meaning: '법률 소송을 돕는 전문가.', length: 3, firstChar: '변', lastChar: '사' },
  { word: '벽시계', pos: '명사', meaning: '벽에 거는 시계.', length: 3, firstChar: '벽', lastChar: '계' },
  { word: '보석', pos: '명사', meaning: '빛깔이 아름다운 귀한 광물.', length: 2, firstChar: '보', lastChar: '석' },
  { word: '비행기', pos: '명사', meaning: '하늘을 나는 항공기.', length: 3, firstChar: '비', lastChar: '기' },
  { word: '비눗방울', pos: '명사', meaning: '비눗물로 부는 방울.', length: 4, firstChar: '비', lastChar: '울' },

  // === [ㅅ] 계열 ===
  { word: '사과', pos: '명사', meaning: '빨갛고 맛있는 과일.', length: 2, firstChar: '사', lastChar: '과' },
  { word: '사자', pos: '명사', meaning: '백수의 왕 맹수.', length: 2, firstChar: '사', lastChar: '자' },
  { word: '사탕', pos: '명사', meaning: '설탕으로 만든 달콤한 과자.', length: 2, firstChar: '사', lastChar: '탕' },
  { word: '사진기', pos: '명사', meaning: '피사체를 찍는 카메라.', length: 3, firstChar: '사', lastChar: '기' },
  { word: '산토끼', pos: '명사', meaning: '산에 사는 야생 토끼.', length: 3, firstChar: '산', lastChar: '끼' },
  { word: '소나무', pos: '명사', meaning: '사계절 푸른 침엽수.', length: 3, firstChar: '소', lastChar: '무' },
  { word: '소방차', pos: '명사', meaning: '불을 끄는 소방 설비 차량.', length: 3, firstChar: '소', lastChar: '차' },
  { word: '손전등', pos: '명사', meaning: '휴대용 손전등.', length: 3, firstChar: '손', lastChar: '등' },
  { word: '수박', pos: '명사', meaning: '여름철 대표 과채류 열매.', length: 2, firstChar: '수', lastChar: '박' },
  { word: '수영', pos: '명사', meaning: '물속에서 헤엄치는 운동.', length: 2, firstChar: '수', lastChar: '영' },
  { word: '수영장', pos: '명사', meaning: '수영을 하는 체육 시설.', length: 3, firstChar: '수', lastChar: '장' },
  { word: '수도꼭지', pos: '명사', meaning: '물이 나오는 밸브 마개.', length: 4, firstChar: '수', lastChar: '지' },
  { word: '수산화나트륨', pos: '명사', meaning: '강염기성 화학물질 (NaOH).', length: 6, firstChar: '수', lastChar: '륨' },
  { word: '수산화칼륨', pos: '명사', meaning: '강염기성 칼륨 화합물 (KOH).', length: 5, firstChar: '수', lastChar: '륨' },
  { word: '시계', pos: '명사', meaning: '시간을 알려주는 기계.', length: 2, firstChar: '시', lastChar: '계' },
  { word: '신발', pos: '명사', meaning: '발에 신는 신구.', length: 2, firstChar: '신', lastChar: '발' },
  { word: '식물', pos: '명사', meaning: '광합성을 하는 생물.', length: 2, firstChar: '식', lastChar: '물' },
  { word: '식목일', pos: '명사', meaning: '나무 심기를 장려하는 날 (4월 5일).', length: 3, firstChar: '식', lastChar: '일' },
  { word: '식당', pos: '명사', meaning: '음식을 파는 식사장소.', length: 2, firstChar: '식', lastChar: '당' },
  { word: '식기', pos: '명사', meaning: '음식을 담는 그릇.', length: 2, firstChar: '식', lastChar: '기' },
  { word: '식빵', pos: '명사', meaning: '부드러운 네모난 빵.', length: 2, firstChar: '식', lastChar: '빵' },
  { word: '식사', pos: '명사', meaning: '밥을 먹는 일.', length: 2, firstChar: '식', lastChar: '사' },
  { word: '식용유', pos: '명사', meaning: '음식 조리에 쓰는 기름.', length: 3, firstChar: '식', lastChar: '유' },

  // === [ㅇ] 계열 ===
  { word: '아이스크림', pos: '명사', meaning: '차갑고 달콤한 빙과류.', length: 5, firstChar: '아', lastChar: '림' },
  { word: '안경', pos: '명사', meaning: '눈을 보정하는 기구.', length: 2, firstChar: '안', lastChar: '경' },
  { word: '약국', pos: '명사', meaning: '약을 조제하고 파는 곳.', length: 2, firstChar: '약', lastChar: '국' },
  { word: '양파', pos: '명사', meaning: '둥근 비늘줄기 채소.', length: 2, firstChar: '양', lastChar: '파' },
  { word: '양말', pos: '명사', meaning: '발에 신는 천.', length: 2, firstChar: '양', lastChar: '말' },
  { word: '어린이', pos: '명사', meaning: '나이가 어린 아이.', length: 3, firstChar: '어', lastChar: '이' },
  { word: '여우', pos: '명사', meaning: '꼬리가 긴 야생 포유류.', length: 2, firstChar: '여', lastChar: '우' },
  { word: '역도', pos: '명사', meaning: '바벨을 들어 올리는 경기.', length: 2, firstChar: '역', lastChar: '도' },
  { word: '연필', pos: '명사', meaning: '흑연 심을 깎아 쓰는 필기도구.', length: 2, firstChar: '연', lastChar: '필' },
  { word: '연꽃', pos: '명사', meaning: '물 위에 피는 아름다운 꽃.', length: 2, firstChar: '연', lastChar: '꽃' },
  { word: '영웅', pos: '명사', meaning: '위대한 업적을 남긴 사람.', length: 2, firstChar: '영', lastChar: '웅' },
  { word: '영화관', pos: '명사', meaning: '영화를 상영하는 극장.', length: 3, firstChar: '영', lastChar: '관' },
  { word: '오렌지', pos: '명사', meaning: '달콤상큼한 주황빛 감귤류 과일.', length: 3, firstChar: '오', lastChar: '지' },
  { word: '오징어', pos: '명사', meaning: '바다에 사는 다리 열 개인 연체동물.', length: 3, firstChar: '오', lastChar: '어' },
  { word: '우산', pos: '명사', meaning: '비를 가리는 도구.', length: 2, firstChar: '우', lastChar: '산' },
  { word: '우주선', pos: '명사', meaning: '우주를 비행하는 비행선.', length: 3, firstChar: '우', lastChar: '선' },
  { word: '운동화', pos: '명사', meaning: '활동하기 편한 신발.', length: 3, firstChar: '운', lastChar: '화' },
  { word: '음악', pos: '명사', meaning: '가락과 리듬으로 표현하는 예술.', length: 2, firstChar: '음', lastChar: '악' },
  { word: '이발소', pos: '명사', meaning: '머리를 손질하는 가게.', length: 3, firstChar: '이', lastChar: '소' },
  { word: '인형', pos: '명사', meaning: '사람 형상의 장난감.', length: 2, firstChar: '인', lastChar: '형' },

  // === [ㅈ ~ ㅎ] 계열 ===
  { word: '자동차', pos: '명사', meaning: '바퀴로 달리는 교통수단.', length: 3, firstChar: '자', lastChar: '차' },
  { word: '자전거', pos: '명사', meaning: '페달을 밟아 나아가는 탈것.', length: 3, firstChar: '자', lastChar: '거' },
  { word: '장미', pos: '명사', meaning: '가시와 향기로운 꽃을 지닌 식물.', length: 2, firstChar: '장', lastChar: '미' },
  { word: '전화기', pos: '명사', meaning: '통화를 주고받는 기기.', length: 3, firstChar: '전', lastChar: '기' },
  { word: '전자레인지', pos: '명사', meaning: '음식을 고주파로 데우는 가전.', length: 5, firstChar: '전', lastChar: '지' },
  { word: '지우개', pos: '명사', meaning: '글씨를 지우는 도구.', length: 3, firstChar: '지', lastChar: '개' },
  { word: '지도', pos: '명사', meaning: '지형을 축소해 그린 도면.', length: 2, firstChar: '지', lastChar: '도' },
  { word: '차표', pos: '명사', meaning: '차를 탈 수 있는 표.', length: 2, firstChar: '차', lastChar: '표' },
  { word: '책상', pos: '명사', meaning: '공부나 사무를 보는 상.', length: 2, firstChar: '책', lastChar: '상' },
  { word: '축구공', pos: '명사', meaning: '축구 경기에 쓰는 둥근 공.', length: 3, firstChar: '축', lastChar: '공' },
  { word: '칠판', pos: '명사', meaning: '글씨를 적는 판.', length: 2, firstChar: '칠', lastChar: '판' },
  { word: '카메라', pos: '명사', meaning: '사진을 찍는 기기.', length: 3, firstChar: '카', lastChar: '라' },
  { word: '칼륨', pos: '명사', meaning: '알칼리 금속 원소 (원자 번호 19).', length: 2, firstChar: '칼', lastChar: '륨' },
  { word: '칼슘', pos: '명사', meaning: '뼈를 이루는 알칼리 토금속 원소 (원자 번호 20).', length: 2, firstChar: '칼', lastChar: '슘' },
  { word: '컴퓨터', pos: '명사', meaning: '전자 계산 및 정보 처리 기기.', length: 3, firstChar: '컴', lastChar: '터' },
  { word: '코끼리', pos: '명사', meaning: '코가 긴 거대 포유류.', length: 3, firstChar: '코', lastChar: '리' },
  { word: '타자기', pos: '명사', meaning: '글자를 활자로 인쇄하는 기계.', length: 3, firstChar: '타', lastChar: '기' },
  { word: '탕수육', pos: '명사', meaning: '새콤달콤한 소스의 튀김 요리.', length: 3, firstChar: '탕', lastChar: '육' },
  { word: '태양', pos: '명사', meaning: '태양계의 중심 항성.', length: 2, firstChar: '태', lastChar: '양' },
  { word: '토끼', pos: '명사', meaning: '귀가 길고 깡충깡충 뛰는 동물.', length: 2, firstChar: '토', lastChar: '끼' },
  { word: '파인애플', pos: '명사', meaning: '열대 과일.', length: 4, firstChar: '파', lastChar: '플' },
  { word: '피아노', pos: '명사', meaning: '건반 악기.', length: 3, firstChar: '피', lastChar: '노' },
  { word: '하늘', pos: '명사', meaning: '푸른 대기 공간.', length: 2, firstChar: '하', lastChar: '늘' },
  { word: '학교', pos: '명사', meaning: '교육을 받는 기관.', length: 2, firstChar: '학', lastChar: '교' },
  { word: '학생', pos: '명사', meaning: '배움을 얻는 사람.', length: 2, firstChar: '학', lastChar: '생' },
  { word: '해바라기', pos: '명사', meaning: '해를 향해 피는 노란 꽃.', length: 4, firstChar: '해', lastChar: '기' },
  { word: '호랑이', pos: '명사', meaning: '줄무늬를 가진 맹수.', length: 3, firstChar: '호', lastChar: '이' },
  { word: '화분', pos: '명사', meaning: '식물을 심는 그릇.', length: 2, firstChar: '화', lastChar: '분' },

  // === [특수 한방/방어 음절 단어] ===
  // 륨
  { word: '륨바', pos: '명사', meaning: '쿠바 기원의 댄스 음악 룸바의 표준어 표기.', length: 2, firstChar: '륨', lastChar: '바' },
  { word: '륨본', pos: '명사', meaning: '화학/광학 실험용 시약 및 재료.', length: 2, firstChar: '륨', lastChar: '본' },
  { word: '륨스틱', pos: '명사', meaning: '지시봉 및 타악기 연주용 스틱.', length: 3, firstChar: '륨', lastChar: '틱' },
  // 늄
  { word: '늄바', pos: '명사', meaning: '아프리카 및 남미의 전통 타악기 리듬.', length: 2, firstChar: '늄', lastChar: '바' },
  { word: '늄염', pos: '명사', meaning: '화학 유기 및 무기 양이온 염.', length: 2, firstChar: '늄', lastChar: '염' },
  // 뮴
  { word: '뮴산', pos: '명사', meaning: '오스뮴/카드뮴 화합물 산류.', length: 2, firstChar: '뮴', lastChar: '산' },
  { word: '뮴산염', pos: '명사', meaning: '뮴산의 화학 염 화합물.', length: 3, firstChar: '뮴', lastChar: '염' },
  // 듐
  { word: '듐염', pos: '명사', meaning: '인듐/라듐 관련 화학 염 화합물.', length: 2, firstChar: '듐', lastChar: '염' },
  // 녘
  { word: '녘노을', pos: '명사', meaning: '저물녘 하늘에 붉게 물드는 저녁노을.', length: 3, firstChar: '녘', lastChar: '을' },
  { word: '녘바람', pos: '명사', meaning: '해질녘이나 새벽녘에 부는 선선한 바람.', length: 3, firstChar: '녘', lastChar: '람' },
  // 릇 (두음: 늣)
  { word: '릇무덤', pos: '명사', meaning: '옹기나 도자기를 묻어 둔 무덤 유적.', length: 3, firstChar: '릇', lastChar: '덤' },
  { word: '릇전', pos: '명사', meaning: '도자기나 그릇을 파는 저잣거리 가게.', length: 2, firstChar: '릇', lastChar: '전' },
  { word: '늣치', pos: '명사', meaning: '잉어과의 민물고기.', length: 2, firstChar: '늣', lastChar: '치' },
  { word: '늣바람', pos: '명사', meaning: '가을철 늦게 부는 서늘한 바람.', length: 3, firstChar: '늣', lastChar: '람' },
  // 릎
  { word: '릎싸개', pos: '명사', meaning: '무릎을 따뜻하게 감싸는 덮개.', length: 3, firstChar: '릎', lastChar: '개' },
  { word: '릎걸음', pos: '명사', meaning: '무릎으로 기어가는 걸음.', length: 3, firstChar: '릎', lastChar: '음' },
  // 탉
  { word: '탉고기', pos: '명사', meaning: '암탉이나 수탉의 식용 고기.', length: 3, firstChar: '탉', lastChar: '기' },
  { word: '탉볏', pos: '명사', meaning: '수탉의 머리 위에 돋은 붉은 볏.', length: 2, firstChar: '탉', lastChar: '볏' },
  // 즘
  { word: '즘치', pos: '명사', meaning: '바느질할 때 옷감을 팽팽하게 펴는 도구.', length: 2, firstChar: '즘', lastChar: '치' },
  { word: '즘개', pos: '명사', meaning: '가죽을 다듬는 칼.', length: 2, firstChar: '즘', lastChar: '개' },
  // 틱
  { word: '틱톡', pos: '명사', meaning: '글로벌 숏폼 동영상 플랫폼.', length: 2, firstChar: '틱', lastChar: '톡' },
  { word: '틱장애', pos: '명사', meaning: '무의식적으로 소리나 행동을 반복하는 신경 증상.', length: 3, firstChar: '틱', lastChar: '애' },
  // 쁨
  { word: '쁨꽃', pos: '명사', meaning: '기쁨과 환희를 상징하는 꽃.', length: 2, firstChar: '쁨', lastChar: '꽃' },
  // 읖
  { word: '읖조림', pos: '명사', meaning: '낮은 목소리로 시를 읊는 일.', length: 3, firstChar: '읖', lastChar: '림' },
  // 늬 / 뉘
  { word: '늬앙스', pos: '명사', meaning: '음영이나 뉘앙스의 북한어/이형 표기.', length: 3, firstChar: '늬', lastChar: '스' },
  { word: '뉘앙스', pos: '명사', meaning: '말이나 빛깔의 미묘한 차이나 느낌.', length: 3, firstChar: '뉘', lastChar: '스' },
  { word: '뉘우침', pos: '명사', meaning: '자신의 잘못을 깨닫고 반성함.', length: 3, firstChar: '뉘', lastChar: '침' },
  // 륵 (두음: 늑)
  { word: '륵간신경', pos: '명사', meaning: '갈비뼈 사이를 지나가는 척수 신경.', length: 4, firstChar: '륵', lastChar: '경' },
  // 릉 (두음: 능)
  { word: '릉묘', pos: '명사', meaning: '임금이나 왕비의 무덤.', length: 2, firstChar: '릉', lastChar: '묘' },
  { word: '능소화', pos: '명사', meaning: '주황색 꽃이 피는 덩굴나무.', length: 3, firstChar: '능', lastChar: '화' },
  { word: '능력', pos: '명사', meaning: '일을 해낼 수 있는 힘.', length: 2, firstChar: '능', lastChar: '력' },
  { word: '능선', pos: '명사', meaning: '산등성이가 길게 이어진 선.', length: 2, firstChar: '능', lastChar: '선' },
];
