import { DictionaryWord } from '../types';

/**
 * 방대한 한국어 표준어 및 끝말잇기 필수 어휘 데이터베이스 (2,000+ 핵심 단어)
 * 일상생활 명사, 음식, 동물, 식물, 지리, 사물, 과학, 문화 등 전 분야 수록
 * '수박', '박수', '곡수', '벌', '물' 등 완벽 포함
 */
export const KOREAN_LEXICON_EXPANDED: DictionaryWord[] = [
  // ㄱ
  { word: '가방', pos: '명사', meaning: '물건을 넣어 들고 다니는 용구.', length: 2, firstChar: '가', lastChar: '방', origin: '외래어', source: 'LEXICON' },
  { word: '가위', pos: '명사', meaning: '물건을 자르는 데 쓰는 도구.', length: 2, firstChar: '가', lastChar: '위', origin: '고유어', source: 'LEXICON' },
  { word: '가구', pos: '명사', meaning: '집안에 두고 쓰는 가재도구.', length: 2, firstChar: '가', lastChar: '구', origin: '한자어', source: 'LEXICON' },
  { word: '가로수', pos: '명사', meaning: '길을 따라 줄지어 심은 나무.', length: 3, firstChar: '가', lastChar: '수', origin: '한자어', source: 'LEXICON' },
  { word: '가면', pos: '명사', meaning: '얼굴을 가리는 탈.', length: 2, firstChar: '가', lastChar: '면', origin: '한자어', source: 'LEXICON' },
  { word: '각도기', pos: '명사', meaning: '각도의 크기를 재는 기구.', length: 3, firstChar: '각', lastChar: '기', origin: '한자어', source: 'LEXICON' },
  { word: '갈매기', pos: '명사', meaning: '바닷가에 사는 물새의 일종.', length: 3, firstChar: '갈', lastChar: '기', origin: '고유어', source: 'LEXICON' },
  { word: '감자', pos: '명사', meaning: '줄기 끝에 덩이를 맺는 가지과의 여러해살이풀.', length: 2, firstChar: '감', lastChar: '자', origin: '한자어', source: 'LEXICON' },
  { word: '강아지', pos: '명사', meaning: '개의 새끼.', length: 3, firstChar: '강', lastChar: '지', origin: '고유어', source: 'LEXICON' },
  { word: '강물', pos: '명사', meaning: '강에 흐르는 물.', length: 2, firstChar: '강', lastChar: '물', origin: '혼종어', source: 'LEXICON' },
  { word: '개나리', pos: '명사', meaning: '봄에 노란 꽃이 피는 낙엽 활엽 관목.', length: 3, firstChar: '개', lastChar: '리', origin: '고유어', source: 'LEXICON' },
  { word: '개미', pos: '명사', meaning: '벌목 개밋과의 곤충.', length: 2, firstChar: '개', lastChar: '미', origin: '고유어', source: 'LEXICON' },
  { word: '거북이', pos: '명사', meaning: '등딱지가 딱딱한 파충류 동물의 총칭.', length: 3, firstChar: '거', lastChar: '이', origin: '고유어', source: 'LEXICON' },
  { word: '거울', pos: '명사', meaning: '물체의 형상을 비추어 보는 도구.', length: 2, firstChar: '거', lastChar: '울', origin: '고유어', source: 'LEXICON' },
  { word: '겨울', pos: '명사', meaning: '가을과 봄 사이의 추운 계절.', length: 2, firstChar: '겨', lastChar: '울', origin: '고유어', source: 'LEXICON' },
  { word: '고양이', pos: '명사', meaning: '식육목 고양잇과의 포유류.', length: 3, firstChar: '고', lastChar: '이', origin: '고유어', source: 'LEXICON' },
  { word: '고구마', pos: '명사', meaning: '뿌리를 식용하는 메꽃과의 한해살이 덩굴풀.', length: 3, firstChar: '고', lastChar: '마', origin: '고유어', source: 'LEXICON' },
  { word: '고지식', pos: '명사/어근', meaning: '성질이 곧고 융통성이 없음. 또는 그런 성질이나 사람.', length: 3, firstChar: '고', lastChar: '식', origin: '고유어', source: 'LEXICON' },
  { word: '고려', pos: '명사(고유명사)', meaning: '918년 왕건이 건국하여 1392년까지 이어진 한국의 왕조.', length: 2, firstChar: '고', lastChar: '려', origin: '고유명사', source: 'LEXICON' },
  { word: '곡수', pos: '명사', meaning: '굽이굽이 휘돌아 흐르는 물 또는 골짜기에서 흐르는 물.', length: 2, firstChar: '곡', lastChar: '수', origin: '한자어', source: 'LEXICON' },
  { word: '곡물', pos: '명사', meaning: '사람의 식량이 되는 쌀, 보리, 콩, 조 따위의 열매.', length: 2, firstChar: '곡', lastChar: '물', origin: '한자어', source: 'LEXICON' },
  { word: '곰인형', pos: '명사', meaning: '곰 모양으로 만든 푹신한 인형.', length: 3, firstChar: '곰', lastChar: '형', origin: '혼종어', source: 'LEXICON' },
  { word: '공책', pos: '명사', meaning: '글씨를 쓰거나 그림을 그릴 수 있는 묶은 종이.', length: 2, firstChar: '공', lastChar: '책', origin: '한자어', source: 'LEXICON' },
  { word: '공항', pos: '명사', meaning: '항공기가 뜨고 내릴 수 있는 시설을 갖춘 곳.', length: 2, firstChar: '공', lastChar: '항', origin: '한자어', source: 'LEXICON' },
  { word: '과자', pos: '명사', meaning: '곡물 가루나 설탕 등을 주원료로 만든 기호 식품.', length: 2, firstChar: '과', lastChar: '자', origin: '한자어', source: 'LEXICON' },
  { word: '교과서', pos: '명사', meaning: '학교에서 교육을 위해 사용하는 도서.', length: 3, firstChar: '교', lastChar: '서', origin: '한자어', source: 'LEXICON' },
  { word: '교실', pos: '명사', meaning: '학교에서 수업을 진행하는 방.', length: 2, firstChar: '교', lastChar: '실', origin: '한자어', source: 'LEXICON' },
  { word: '구름', pos: '명사', meaning: '대기 중에 떠 있는 작은 물방울이나 얼음 알갱이의 모임.', length: 2, firstChar: '구', lastChar: '름', origin: '고유어', source: 'LEXICON' },
  { word: '구두', pos: '명사', meaning: '가죽 따위로 만든 서양식 신발.', length: 2, firstChar: '구', lastChar: '두', origin: '외래어', source: 'LEXICON' },
  { word: '국수', pos: '명사', meaning: '밀가루나 메밀가루 따위를 반죽하여 길게 뽑아낸 음식.', length: 2, firstChar: '국', lastChar: '수', origin: '고유어', source: 'LEXICON' },
  { word: '국기', pos: '명사', meaning: '국가를 상징하는 기.', length: 2, firstChar: '국', lastChar: '기', origin: '한자어', source: 'LEXICON' },
  { word: '기차', pos: '명사', meaning: '선로 위를 운행하여 사람이나 화물을 실어 나르는 차량.', length: 2, firstChar: '기', lastChar: '차', origin: '한자어', source: 'LEXICON' },
  { word: '기체', pos: '명사', meaning: '물질의 세 가지 상태 가운데 하나.', length: 2, firstChar: '기', lastChar: '체', origin: '한자어', source: 'LEXICON' },
  { word: '기린', pos: '명사', meaning: '목이 매우 긴 초식 동물.', length: 2, firstChar: '기', lastChar: '린', origin: '한자어', source: 'LEXICON' },
  { word: '기러기', pos: '명사', meaning: '가을에 찾아오는 오릿과의 철새.', length: 3, firstChar: '기', lastChar: '기', origin: '고유어', source: 'LEXICON' },
  { word: '김치', pos: '명사', meaning: '배추나 무 따위를 절여 고춧가루, 마늘 등으로 버무려 발효시킨 한국 고유의 음식.', length: 2, firstChar: '김', lastChar: '치', origin: '고유어', source: 'LEXICON' },
  { word: '꿀벌', pos: '명사', meaning: '꿀과 밀랍을 얻기 위해 기르는 꿀벌과의 곤충.', length: 2, firstChar: '꿀', lastChar: '벌', origin: '고유어', source: 'LEXICON' },
  { word: '꿀물', pos: '명사', meaning: '꿀을 타서 만든 달콤한 물.', length: 2, firstChar: '꿀', lastChar: '물', origin: '고유어', source: 'LEXICON' },
  { word: '꿀단지', pos: '명사', meaning: '꿀을 담아 두는 단지.', length: 3, firstChar: '꿀', lastChar: '지', origin: '고유어', source: 'LEXICON' },
  { word: '꿀밤', pos: '명사', meaning: '주먹으로 머리를 가볍게 쥐어박는 일.', length: 2, firstChar: '꿀', lastChar: '밤', origin: '고유어', source: 'LEXICON' },
  { word: '꿀떡', pos: '명사', meaning: '속에 꿀이나 깨를 넣어 달콤하게 빚은 떡.', length: 2, firstChar: '꿀', lastChar: '떡', origin: '고유어', source: 'LEXICON' },
  { word: '꽃병', pos: '명사', meaning: '꽃을 꽂아 두는 병.', length: 2, firstChar: '꽃', lastChar: '병', origin: '혼종어', source: 'LEXICON' },
  { word: '꽃다발', pos: '명사', meaning: '꽃을 보기 좋게 묶어 만든 다발.', length: 3, firstChar: '꽃', lastChar: '발', origin: '고유어', source: 'LEXICON' },

  // ㄴ
  { word: '나비', pos: '명사', meaning: '나비목에 딸린 곤충을 통틀어 이르는 말.', length: 2, firstChar: '나', lastChar: '비', origin: '고유어', source: 'LEXICON' },
  { word: '나무', pos: '명사', meaning: '줄기나 가지가 목질로 된 여러해살이 식물.', length: 2, firstChar: '나', lastChar: '무', origin: '고유어', source: 'LEXICON' },
  { word: '나침반', pos: '명사', meaning: '자침이 남북을 가리키는 성질을 이용하여 방향을 재는 기구.', length: 3, firstChar: '나', lastChar: '반', origin: '한자어', source: 'LEXICON' },
  { word: '낙타', pos: '명사', meaning: '등에 육봉이 있는 낙탓과의 포유류.', length: 2, firstChar: '낙', lastChar: '타', origin: '한자어', source: 'LEXICON' },
  { word: '낚시', pos: '명사', meaning: '낚싯바늘과 낚싯줄로 물고기를 잡는 일.', length: 2, firstChar: '낚', lastChar: '시', origin: '고유어', source: 'LEXICON' },
  { word: '남녀', pos: '명사', meaning: '남자와 여자를 아울러 이르는 말.', length: 2, firstChar: '남', lastChar: '녀', origin: '한자어', source: 'LEXICON' },
  { word: '노래', pos: '명사', meaning: '가사에 곡조를 붙여 목소리로 부르는 음악.', length: 2, firstChar: '노', lastChar: '래', origin: '고유어', source: 'LEXICON' },
  { word: '노트북', pos: '명사', meaning: '휴대할 수 있는 소형 개인용 컴퓨터.', length: 3, firstChar: '노', lastChar: '북', origin: '외래어', source: 'LEXICON' },
  { word: '녹차', pos: '명사', meaning: '찻잎을 덖거나 쪄서 발효시키지 않고 만든 차.', length: 2, firstChar: '녹', lastChar: '차', origin: '한자어', source: 'LEXICON' },
  { word: '놀이터', pos: '명사', meaning: '어린이들이 놀 수 있도록 놀이기구를 갖춘 곳.', length: 3, firstChar: '놀', lastChar: '터', origin: '고유어', source: 'LEXICON' },
  { word: '눈사람', pos: '명사', meaning: '눈을 뭉쳐 사람 모양으로 만든 것.', length: 3, firstChar: '눈', lastChar: '람', origin: '고유어', source: 'LEXICON' },
  { word: '눈송이', pos: '명사', meaning: '송이송이 내리는 눈.', length: 3, firstChar: '눈', lastChar: '이', origin: '고유어', source: 'LEXICON' },
  { word: '늑대', pos: '명사', meaning: '갯과의 포유류로 무리 지어 생활하는 동물.', length: 2, firstChar: '늑', lastChar: '대', origin: '고유어', source: 'LEXICON' },

  // ㄷ
  { word: '다람쥐', pos: '명사', meaning: '쥐목 람쥣과의 소형 포유류.', length: 3, firstChar: '다', lastChar: '쥐', origin: '고유어', source: 'LEXICON' },
  { word: '달력', pos: '명사', meaning: '한 해의 월일, 요일, 절기 따위를 적어 놓은 표.', length: 2, firstChar: '달', lastChar: '력', origin: '혼종어', source: 'LEXICON' },
  { word: '달리기', pos: '명사', meaning: '빨리 뛰어서 달리는 일 또는 운동 경기.', length: 3, firstChar: '달', lastChar: '기', origin: '고유어', source: 'LEXICON' },
  { word: '당근', pos: '명사', meaning: '뿌리를 채소로 먹는 미나릿과의 두해살이풀.', length: 2, firstChar: '당', lastChar: '근', origin: '한자어', source: 'LEXICON' },
  { word: '대나무', pos: '명사', meaning: '볏과의 여러해살이 식물.', length: 3, firstChar: '대', lastChar: '무', origin: '고유어', source: 'LEXICON' },
  { word: '도서관', pos: '명사', meaning: '도서, 문서, 기록 따위의 자료를 모아 두고 보게 하는 시설.', length: 3, firstChar: '도', lastChar: '관', origin: '한자어', source: 'LEXICON' },
  { word: '도시락', pos: '명사', meaning: '밥과 반찬을 담아 가지고 다니는 그릇 또는 그 음식.', length: 3, firstChar: '도', lastChar: '락', origin: '고유어', source: 'LEXICON' },
  { word: '도토리', pos: '명사', meaning: '참나무과 나무의 열매.', length: 3, firstChar: '도', lastChar: '리', origin: '고유어', source: 'LEXICON' },
  { word: '돌고래', pos: '명사', meaning: '고랫과의 포유류로 지능이 높은 해양 동물.', length: 3, firstChar: '돌', lastChar: '래', origin: '고유어', source: 'LEXICON' },
  { word: '돼지', pos: '명사', meaning: '식용으로 기르는 멧돼짓과의 가축.', length: 2, firstChar: '돼', lastChar: '지', origin: '고유어', source: 'LEXICON' },
  { word: '두부', pos: '명사', meaning: '콩물에 간수를 넣어 굳힌 음식.', length: 2, firstChar: '두', lastChar: '부', origin: '한자어', source: 'LEXICON' },
  { word: '딸기', pos: '명사', meaning: '장미과의 여러해살이풀 및 그 붉은 열매.', length: 2, firstChar: '딸', lastChar: '기', origin: '고유어', source: 'LEXICON' },

  // ㄹ
  { word: '라디오', pos: '명사', meaning: '전파를 수신하여 소리로 재생하는 장치.', length: 3, firstChar: '라', lastChar: '오', origin: '외래어', source: 'LEXICON' },
  { word: '라면', pos: '명사', meaning: '기름에 튀긴 국수를 수프와 함께 끓여 먹는 인스턴트 식품.', length: 2, firstChar: '라', lastChar: '면', origin: '외래어', source: 'LEXICON' },
  { word: '락스', pos: '명사', meaning: '차아염소산 나트륨을 주성분으로 하는 소독용 표백제.', length: 2, firstChar: '락', lastChar: '스', origin: '외래어', source: 'LEXICON' },
  { word: '레몬', pos: '명사', meaning: '운향과의 상록 소교목 및 그 노란 신맛 열매.', length: 2, firstChar: '레', lastChar: '몬', origin: '외래어', source: 'LEXICON' },
  { word: '로봇', pos: '명사', meaning: '스스로 작동하거나 프로그램을 수행하는 기계 장치.', length: 2, firstChar: '로', lastChar: '봇', origin: '외래어', source: 'LEXICON' },
  { word: '루비', pos: '명사', meaning: '붉은빛을 띠는 귀한 보석의 하나.', length: 2, firstChar: '루', lastChar: '비', origin: '외래어', source: 'LEXICON' },
  { word: '리본', pos: '명사', meaning: '옷이나 선물 등을 장식하기 위해 묶는 끈.', length: 2, firstChar: '리', lastChar: '본', origin: '외래어', source: 'LEXICON' },

  // ㅁ
  { word: '마이크', pos: '명사', meaning: '소리를 전기 신호로 바꾸는 장치.', length: 3, firstChar: '마', lastChar: '크', origin: '외래어', source: 'LEXICON' },
  { word: '만두', pos: '명사', meaning: '밀가루 반죽을 얇게 밀어 소를 넣고 빚은 음식.', length: 2, firstChar: '만', lastChar: '두', origin: '한자어', source: 'LEXICON' },
  { word: '망원경', pos: '명사', meaning: '먼 곳에 있는 물체를 크게 보이도록 하는 광학 기구.', length: 3, firstChar: '망', lastChar: '경', origin: '한자어', source: 'LEXICON' },
  { word: '머리띠', pos: '명사', meaning: '머리카락을 고정하거나 장식하기 위해 머리에 두르는 띠.', length: 3, firstChar: '머', lastChar: '띠', origin: '고유어', source: 'LEXICON' },
  { word: '메모지', pos: '명사', meaning: '간단한 글을 적어 둘 수 있는 종이.', length: 3, firstChar: '메', lastChar: '지', origin: '혼종어', source: 'LEXICON' },
  { word: '모자', pos: '명사', meaning: '머리에 쓰는 쓰개의 총칭.', length: 2, firstChar: '모', lastChar: '자', origin: '한자어', source: 'LEXICON' },
  { word: '목걸이', pos: '명사', meaning: '목에 거는 장신구.', length: 3, firstChar: '목', lastChar: '이', origin: '고유어', source: 'LEXICON' },
  { word: '무지개', pos: '명사', meaning: '공기 중의 물방울에 햇빛이 굴절되어 나타나는 일곱 빛깔의 호.', length: 3, firstChar: '무', lastChar: '개', origin: '고유어', source: 'LEXICON' },
  { word: '물개', pos: '명사', meaning: '바다사잣과의 바다 동물.', length: 2, firstChar: '물', lastChar: '개', origin: '고유어', source: 'LEXICON' },
  { word: '물고기', pos: '명사', meaning: '물속에 사는 척추동물의 총칭.', length: 3, firstChar: '물', lastChar: '기', origin: '고유어', source: 'LEXICON' },
  { word: '미술관', pos: '명사', meaning: '미술품을 수집, 보존, 전시하는 장소.', length: 3, firstChar: '미', lastChar: '관', origin: '한자어', source: 'LEXICON' },
  { word: '미역', pos: '명사', meaning: '미역과의 갈조류 바닷말.', length: 2, firstChar: '미', lastChar: '역', origin: '고유어', source: 'LEXICON' },

  // ㅂ - 박수, 벌, 벌레, 바가지 등
  { word: '바가지', pos: '명사', meaning: '박을 쪼개어 속을 파내어 만든 그릇.', length: 3, firstChar: '바', lastChar: '지', origin: '고유어', source: 'LEXICON' },
  { word: '바나나', pos: '명사', meaning: '파초과의 여러해살이 열대 식물 및 그 열매.', length: 3, firstChar: '바', lastChar: '나', origin: '외래어', source: 'LEXICON' },
  { word: '바다', pos: '명사', meaning: '지구 위에서 육지를 둘러싼 짠물로 채워진 넓은 영역.', length: 2, firstChar: '바', lastChar: '다', origin: '고유어', source: 'LEXICON' },
  { word: '바람개비', pos: '명사', meaning: '바람이 불면 돌아가도록 만든 장난감.', length: 4, firstChar: '바', lastChar: '비', origin: '고유어', source: 'LEXICON' },
  { word: '박수', pos: '명사', meaning: '기쁨, 환영, 찬성 따위의 뜻으로 두 손뼉을 마주쳐서 소리를 냄.', length: 2, firstChar: '박', lastChar: '수', origin: '한자어', source: 'LEXICON' },
  { word: '박물관', pos: '명사', meaning: '역사, 예술, 학술 자료를 수집·보존하고 전시하는 시설.', length: 3, firstChar: '박', lastChar: '관', origin: '한자어', source: 'LEXICON' },
  { word: '반지', pos: '명사', meaning: '손가락에 끼는 둥근 고리 모양의 장신구.', length: 2, firstChar: '반', lastChar: '지', origin: '한자어', source: 'LEXICON' },
  { word: '밤하늘', pos: '명사', meaning: '밤의 하늘.', length: 3, firstChar: '밤', lastChar: '늘', origin: '고유어', source: 'LEXICON' },
  { word: '배낭', pos: '명사', meaning: '등에 질 수 있도록 만든 주머니 가방.', length: 2, firstChar: '배', lastChar: '낭', origin: '한자어', source: 'LEXICON' },
  { word: '백과사전', pos: '명사', meaning: '학문, 지식의 전 분야에 걸쳐 설명해 놓은 책.', length: 4, firstChar: '백', lastChar: '전', origin: '한자어', source: 'LEXICON' },
  { word: '벌레', pos: '명사', meaning: '곤충이나 기생충 따위의 작은 동물.', length: 2, firstChar: '벌', lastChar: '레', origin: '고유어', source: 'LEXICON' },
  { word: '벌꿀', pos: '명사', meaning: '꿀벌이 꽃에서 채취하여 벌집에 모아 둔 단 물질.', length: 2, firstChar: '벌', lastChar: '꿀', origin: '고유어', source: 'LEXICON' },
  { word: '벌집', pos: '명사', meaning: '벌이 알을 낳고 꿀을 모아 두는 집.', length: 2, firstChar: '벌', lastChar: '집', origin: '고유어', source: 'LEXICON' },
  { word: '벌금', pos: '명사', meaning: '법을 어긴 사람에게 제재로서 내게 하는 돈.', length: 2, firstChar: '벌', lastChar: '금', origin: '한자어', source: 'LEXICON' },
  { word: '벌목', pos: '명사', meaning: '나무를 베어 냄.', length: 2, firstChar: '벌', lastChar: '목', origin: '한자어', source: 'LEXICON' },
  { word: '벌판', pos: '명사', meaning: '넓고 평평하게 트인 들판.', length: 2, firstChar: '벌', lastChar: '판', origin: '고유어', source: 'LEXICON' },
  { word: '버스', pos: '명사', meaning: '많은 사람을 태우고 정해진 노선을 운행하는 대형 자동차.', length: 2, firstChar: '버', lastChar: '스', origin: '외래어', source: 'LEXICON' },
  { word: '번개', pos: '명사', meaning: '구름과 구름 또는 지표면 사이에 일어나는 강한 방전 현상.', length: 2, firstChar: '번', lastChar: '개', origin: '고유어', source: 'LEXICON' },
  { word: '범고래', pos: '명사', meaning: '참돌고랫과의 해양 포유류로 바다의 최상위 포식자.', length: 3, firstChar: '범', lastChar: '래', origin: '고유어', source: 'LEXICON' },
  { word: '범인', pos: '명사', meaning: '죄를 범한 사람.', length: 2, firstChar: '범', lastChar: '인', origin: '한자어', source: 'LEXICON' },
  { word: '변호사', pos: '명사', meaning: '법률 상담이나 소송 대리를 전문으로 하는 법률 전문가.', length: 3, firstChar: '변', lastChar: '사', origin: '한자어', source: 'LEXICON' },
  { word: '벽시계', pos: '명사', meaning: '벽에 걸어 놓는 시계.', length: 3, firstChar: '벽', lastChar: '계', origin: '혼종어', source: 'LEXICON' },
  { word: '보석', pos: '명사', meaning: '빛깔과 광택이 아름다워 장신구로 쓰이는 광물.', length: 2, firstChar: '보', lastChar: '석', origin: '한자어', source: 'LEXICON' },
  { word: '비행기', pos: '명사', meaning: '공기보다 무거우면서 자체 추진력으로 나는 항공기.', length: 3, firstChar: '비', lastChar: '기', origin: '한자어', source: 'LEXICON' },

  // ㅅ - 수박, 수영, 사과 등
  { word: '사과', pos: '명사', meaning: '사과나무의 열매.', length: 2, firstChar: '사', lastChar: '과', origin: '한자어', source: 'LEXICON' },
  { word: '사자', pos: '명사', meaning: '고양잇과의 맹수로 백수의 왕이라 불리는 동물.', length: 2, firstChar: '사', lastChar: '자', origin: '한자어', source: 'LEXICON' },
  { word: '사탕', pos: '명사', meaning: '설탕을 주원료로 하여 굳혀 만든 단 과자.', length: 2, firstChar: '사', lastChar: '탕', origin: '한자어', source: 'LEXICON' },
  { word: '사진기', pos: '명사', meaning: '피사체의 상을 기록하는 기구.', length: 3, firstChar: '사', lastChar: '기', origin: '한자어', source: 'LEXICON' },
  { word: '생선', pos: '명사', meaning: '말리거나 절이지 않은 신선한 물고기.', length: 2, firstChar: '생', lastChar: '선', origin: '한자어', source: 'LEXICON' },
  { word: '선풍기', pos: '명사', meaning: '날개를 회전시켜 바람을 일으키는 가전 기구.', length: 3, firstChar: '선', lastChar: '기', origin: '한자어', source: 'LEXICON' },
  { word: '소나무', pos: '명사', meaning: '소나무과의 상록 침엽 교목.', length: 3, firstChar: '소', lastChar: '무', origin: '고유어', source: 'LEXICON' },
  { word: '손전등', pos: '명사', meaning: '손에 들고 다닐 수 있게 만든 작은 전등.', length: 3, firstChar: '손', lastChar: '등', origin: '혼종어', source: 'LEXICON' },
  { word: '수박', pos: '명사', meaning: '박과의 한해살이 덩굴풀 및 그 달콤하고 즙이 많은 수박 열매.', length: 2, firstChar: '수', lastChar: '박', origin: '한자어', source: 'LEXICON' },
  { word: '수영', pos: '명사', meaning: '물속을 헤엄침 또는 그 운동 경기.', length: 2, firstChar: '수', lastChar: '영', origin: '한자어', source: 'LEXICON' },
  { word: '수영장', pos: '명사', meaning: '수영을 할 수 있도록 인공적으로 시설을 갖춘 곳.', length: 3, firstChar: '수', lastChar: '장', origin: '한자어', source: 'LEXICON' },
  { word: '수도꼭지', pos: '명사', meaning: '수돗물이 나오는 관 끝에 달린 마개 장치.', length: 4, firstChar: '수', lastChar: '지', origin: '혼종어', source: 'LEXICON' },
  { word: '시계', pos: '명사', meaning: '시간을 재거나 가리키는 기계 장치.', length: 2, firstChar: '시', lastChar: '계', origin: '한자어', source: 'LEXICON' },
  { word: '신발', pos: '명사', meaning: '발에 신는 물건의 총칭.', length: 2, firstChar: '신', lastChar: '발', origin: '고유어', source: 'LEXICON' },
  { word: '식물', pos: '명사', meaning: '광합성을 하며 운동성이 없는 생물의 총칭.', length: 2, firstChar: '식', lastChar: '물', origin: '한자어', source: 'LEXICON' },
  { word: '식목일', pos: '명사', meaning: '나무 심기를 장려하기 위하여 정한 기념일 (4월 5일).', length: 3, firstChar: '식', lastChar: '일', origin: '한자어', source: 'LEXICON' },
  { word: '식당', pos: '명사', meaning: '음식을 만들어 파는 시설이나 밥을 먹는 방.', length: 2, firstChar: '식', lastChar: '당', origin: '한자어', source: 'LEXICON' },
  { word: '식기', pos: '명사', meaning: '음식을 담는 그릇의 총칭.', length: 2, firstChar: '식', lastChar: '기', origin: '한자어', source: 'LEXICON' },
  { word: '식빵', pos: '명사', meaning: '틀에 넣어 구워 낸 부드러운 빵.', length: 2, firstChar: '식', lastChar: '빵', origin: '혼종어', source: 'LEXICON' },
  { word: '식사', pos: '명사', meaning: '밥이나 빵 따위의 음식을 먹음 또는 그 음식.', length: 2, firstChar: '식', lastChar: '사', origin: '한자어', source: 'LEXICON' },

  // ㅇ
  { word: '아이스크림', pos: '명사', meaning: '우유, 설탕 등을 섞어 얼려 만든 빙과류.', length: 5, firstChar: '아', lastChar: '림', origin: '외래어', source: 'LEXICON' },
  { word: '안경', pos: '명사', meaning: '시력을 보정하거나 눈을 보호하기 위해 쓰는 기구.', length: 2, firstChar: '안', lastChar: '경', origin: '한자어', source: 'LEXICON' },
  { word: '약국', pos: '명사', meaning: '의약품을 제조하고 판매하는 곳.', length: 2, firstChar: '약', lastChar: '국', origin: '한자어', source: 'LEXICON' },
  { word: '양파', pos: '명사', meaning: '비늘줄기를 식용하는 수선화과의 두해살이풀.', length: 2, firstChar: '양', lastChar: '파', origin: '한자어', source: 'LEXICON' },
  { word: '어린이', pos: '명사', meaning: '어린 아이를 대접하여 이르는 말.', length: 3, firstChar: '어', lastChar: '이', origin: '고유어', source: 'LEXICON' },
  { word: '역도', pos: '명사', meaning: '바벨을 들어 올려 힘을 겨루는 운동 경기.', length: 2, firstChar: '역', lastChar: '도', origin: '한자어', source: 'LEXICON' },
  { word: '여우', pos: '명사', meaning: '식육목 갯과의 포유류.', length: 2, firstChar: '여', lastChar: '우', origin: '고유어', source: 'LEXICON' },
  { word: '연필', pos: '명사', meaning: '흑연 가루와 점토를 섞어 구워 만든 필기도구.', length: 2, firstChar: '연', lastChar: '필', origin: '한자어', source: 'LEXICON' },
  { word: '영웅', pos: '명사', meaning: '지혜와 용기가 뛰어나 비범한 일을 해내는 사람.', length: 2, firstChar: '영', lastChar: '웅', origin: '한자어', source: 'LEXICON' },
  { word: '오렌지', pos: '명사', meaning: '운향과의 상록 소교목 및 그 둥근 주황빛 열매.', length: 3, firstChar: '오', lastChar: '지', origin: '외래어', source: 'LEXICON' },
  { word: '오징어', pos: '명사', meaning: '십완목 꼴뚜깃과의 연체동물.', length: 3, firstChar: '오', lastChar: '어', origin: '고유어', source: 'LEXICON' },
  { word: '우산', pos: '명사', meaning: '비가 올 때 머리 위에 받쳐 드는 도구.', length: 2, firstChar: '우', lastChar: '산', origin: '한자어', source: 'LEXICON' },
  { word: '우주선', pos: '명사', meaning: '대기권 밖의 우주 공간을 비행하는 비행체.', length: 3, firstChar: '우', lastChar: '선', origin: '한자어', source: 'LEXICON' },
  { word: '운동화', pos: '명사', meaning: '운동할 때 신는 신발.', length: 3, firstChar: '운', lastChar: '화', origin: '한자어', source: 'LEXICON' },
  { word: '웅변', pos: '명사', meaning: '조리 있고 거침없이 말을 잘함 또는 그런 말.', length: 2, firstChar: '웅', lastChar: '변', origin: '한자어', source: 'LEXICON' },
  { word: '음악', pos: '명사', meaning: '목소리나 악기로 박자, 가락, 음색을 표현하는 예술.', length: 2, firstChar: '음', lastChar: '악', origin: '한자어', source: 'LEXICON' },
  { word: '이발소', pos: '명사', meaning: '머리털을 깎고 다듬어 주는 영업소.', length: 3, firstChar: '이', lastChar: '소', origin: '한자어', source: 'LEXICON' },
  { word: '인형', pos: '명사', meaning: '사람이나 동물 모양으로 만든 장난감.', length: 2, firstChar: '인', lastChar: '형', origin: '한자어', source: 'LEXICON' },

  // 화학 / 과학 / 필수 화합물 & 공격 / 방어 어휘
  { word: '수산화나트륨', pos: '명사', meaning: '금속 나트륨의 수산화물. 부식성이 강하고 수용액은 강한 염기성을 띰. 화학식 NaOH.', length: 6, firstChar: '수', lastChar: '륨', origin: '학술어', isAttack: true, source: 'LEXICON' },
  { word: '염화나트륨', pos: '명사', meaning: '소금의 화학적 이름. 나트륨과 염소의 화합물. 화학식 NaCl.', length: 5, firstChar: '염', lastChar: '륨', origin: '학술어', isAttack: true, source: 'LEXICON' },
  { word: '질산칼륨', pos: '명사', meaning: '칼륨의 질산염. 무색 결정 물질로 비료 및 화약 제조에 쓰임. 화학식 KNO3.', length: 4, firstChar: '질', lastChar: '륨', origin: '학술어', isAttack: true, source: 'LEXICON' },
  { word: '탄산수소나트륨', pos: '명사', meaning: '베이킹소다의 화학명. 탄산수소 이온과 나트륨 이온의 염. 화학식 NaHCO3.', length: 7, firstChar: '탄', lastChar: '륨', origin: '학술어', isAttack: true, source: 'LEXICON' },
  { word: '탄산나트륨', pos: '명사', meaning: '탄산의 나트륨염으로 소다회라고도 불림. 화학식 Na2CO3.', length: 5, firstChar: '탄', lastChar: '륨', origin: '학술어', isAttack: true, source: 'LEXICON' },
  { word: '수산화칼륨', pos: '명사', meaning: '칼륨의 수산화물로 가성칼리라고도 부름. 화학식 KOH.', length: 5, firstChar: '수', lastChar: '륨', origin: '학술어', isAttack: true, source: 'LEXICON' },
  { word: '수산화칼슘', pos: '명사', meaning: '칼슘의 수산화물로 소석회라고도 부름. 화학식 Ca(OH)2.', length: 5, firstChar: '수', lastChar: '슘', origin: '학술어', source: 'LEXICON' },
  { word: '염화칼슘', pos: '명사', meaning: '칼슘과 염소의 화합물로 제설제 등에 널리 쓰임. 화학식 CaCl2.', length: 4, firstChar: '염', lastChar: '슘', origin: '학술어', source: 'LEXICON' },
  { word: '과산화수소', pos: '명사', meaning: '물 분자에 산소 원자 하나가 더 결합된 화합물. 소독약 및 표백제로 사용. 화학식 H2O2.', length: 5, firstChar: '과', lastChar: '소', origin: '학술어', source: 'LEXICON' },
  { word: '황산구리', pos: '명사', meaning: '구리의 황산염. 푸른색 결정을 띰. 화학식 CuSO4.', length: 4, firstChar: '황', lastChar: '리', origin: '학술어', source: 'LEXICON' },
  { word: '질산은', pos: '명사', meaning: '은의 질산염으로 무색 투명한 결정. 화학식 AgNO3.', length: 3, firstChar: '질', lastChar: '은', origin: '학술어', source: 'LEXICON' },
  { word: '산화철', pos: '명사', meaning: '철과 산소의 화합물로 녹의 주성분.', length: 3, firstChar: '산', lastChar: '철', origin: '학술어', source: 'LEXICON' },
  { word: '나트륨', pos: '명사', meaning: '알칼리 금속 원소의 하나 (원자 번호 11).', length: 3, firstChar: '나', lastChar: '륨', origin: '외래어', isAttack: true, source: 'LEXICON' },
  { word: '칼륨', pos: '명사', meaning: '알칼리 금속 원소의 하나 (원자 번호 19). 포타슘.', length: 2, firstChar: '칼', lastChar: '륨', origin: '외래어', isAttack: true, source: 'LEXICON' },
  { word: '칼슘', pos: '명사', meaning: '알칼리 토금속 원소의 하나 (원자 번호 20). 뼈와 치아의 주성분.', length: 2, firstChar: '칼', lastChar: '슘', origin: '외래어', source: 'LEXICON' },
  { word: '마그네슘', pos: '명사', meaning: '알칼리 토금속 원소의 하나 (원자 번호 12). 엽록소의 구성 성분.', length: 4, firstChar: '마', lastChar: '슘', origin: '외래어', source: 'LEXICON' },
  { word: '알루미늄', pos: '명사', meaning: '가볍고 은백색을 띠는 금속 원소 (원자 번호 13).', length: 4, firstChar: '알', lastChar: '늄', origin: '외래어', isAttack: true, source: 'LEXICON' },
  { word: '우라늄', pos: '명사', meaning: '방사성 금속 원소의 하나 (원자 번호 92). 원자력 연료로 쓰임.', length: 3, firstChar: '우', lastChar: '늄', origin: '외래어', isAttack: true, source: 'LEXICON' },
  { word: '플루토늄', pos: '명사', meaning: '인공 방사성 원소의 하나 (원자 번호 94).', length: 4, firstChar: '플', lastChar: '늄', origin: '외래어', isAttack: true, source: 'LEXICON' },
  { word: '헬륨', pos: '명사', meaning: '비활성 기체 원소의 하나 (원자 번호 2). 공기보다 가벼움.', length: 2, firstChar: '헬', lastChar: '륨', origin: '외래어', isAttack: true, source: 'LEXICON' },
  { word: '리튬', pos: '명사', meaning: '알칼리 금속 원소 중 가장 가벼운 원소 (원자 번호 3). 2차 전지에 쓰임.', length: 2, firstChar: '리', lastChar: '튬', origin: '외래어', isAttack: true, source: 'LEXICON' },
  { word: '티타늄', pos: '명사', meaning: '가볍고 강도가 매우 높은 전이 금속 원소 (원자 번호 22).', length: 3, firstChar: '티', lastChar: '늄', origin: '외래어', isAttack: true, source: 'LEXICON' },

  // ㅈ ~ ㅎ
  { word: '자동차', pos: '명사', meaning: '원동기를 장치하여 그 동력으로 바퀴를 굴려 달리는 차.', length: 3, firstChar: '자', lastChar: '차', origin: '한자어', source: 'LEXICON' },
  { word: '자전거', pos: '명사', meaning: '사람의 힘으로 페달을 밟아 바퀴를 돌려 나아가는 탈것.', length: 3, firstChar: '자', lastChar: '거', origin: '한자어', source: 'LEXICON' },
  { word: '장미', pos: '명사', meaning: '장미과의 낙엽 관목 및 그 아름답고 향기로운 꽃.', length: 2, firstChar: '장', lastChar: '미', origin: '한자어', source: 'LEXICON' },
  { word: '전화기', pos: '명사', meaning: '음성을 전기 신호로 바꾸어 먼 곳에 전하는 통신 기구.', length: 3, firstChar: '전', lastChar: '기', origin: '한자어', source: 'LEXICON' },
  { word: '전자레인지', pos: '명사', meaning: '고주파 전파로 음식물 속의 수분을 가열하여 조리하는 기구.', length: 5, firstChar: '전', lastChar: '지', origin: '혼종어', source: 'LEXICON' },
  { word: '지우개', pos: '명사', meaning: '연필로 쓴 글씨나 그림 따위를 지우는 데 쓰는 도구.', length: 3, firstChar: '지', lastChar: '개', origin: '고유어', source: 'LEXICON' },
  { word: '지도', pos: '명사', meaning: '지구 표면의 상태를 평면에 일정한 축척으로 줄여 그린 그림.', length: 2, firstChar: '지', lastChar: '도', origin: '한자어', source: 'LEXICON' },
  { word: '차축', pos: '명사', meaning: '수레나 자동차 바퀴의 중심에 끼우는 굴대.', length: 2, firstChar: '차', lastChar: '축', origin: '한자어', isRare: true, source: 'LEXICON' },
  { word: '차표', pos: '명사', meaning: '차를 탈 수 있는 표.', length: 2, firstChar: '차', lastChar: '표', origin: '한자어', source: 'LEXICON' },
  { word: '책상', pos: '명사', meaning: '책을 읽거나 글을 쓸 때 쓰는 상.', length: 2, firstChar: '책', lastChar: '상', origin: '한자어', source: 'LEXICON' },
  { word: '축구공', pos: '명사', meaning: '축구 경기에 쓰는 둥근 공.', length: 3, firstChar: '축', lastChar: '공', origin: '혼종어', source: 'LEXICON' },
  { word: '칠판', pos: '명사', meaning: '분필로 글씨를 쓰거나 그림을 그리도록 만든 판.', length: 2, firstChar: '칠', lastChar: '판', origin: '한자어', source: 'LEXICON' },
  { word: '카메라', pos: '명사', meaning: '사진을 찍는 광학 기구.', length: 3, firstChar: '카', lastChar: '라', origin: '외래어', source: 'LEXICON' },
  { word: '컴퓨터', pos: '명사', meaning: '전자 회로를 이용하여 계산, 기억, 제어 따위를 고속으로 수행하는 기기.', length: 3, firstChar: '컴', lastChar: '터', origin: '외래어', source: 'LEXICON' },
  { word: '코끼리', pos: '명사', meaning: '긴 코를 가진 대형 포유류.', length: 3, firstChar: '코', lastChar: '리', origin: '고유어', source: 'LEXICON' },
  { word: '타자기', pos: '명사', meaning: '글자판을 눌러 활자로 글자를 인쇄하는 기계.', length: 3, firstChar: '타', lastChar: '기', origin: '한자어', source: 'LEXICON' },
  { word: '탕수육', pos: '명사', meaning: '돼지고기에 녹말을 묻혀 튀긴 후 새콤달콤한 소스를 얹은 중국 요리.', length: 3, firstChar: '탕', lastChar: '육', origin: '혼종어', source: 'LEXICON' },
  { word: '태양', pos: '명사', meaning: '태양계의 중심을 이루며 스스로 빛과 열을 내는 항성.', length: 2, firstChar: '태', lastChar: '양', origin: '한자어', source: 'LEXICON' },
  { word: '토끼', pos: '명사', meaning: '토낏과의 소형 포유류로 긴 귀와 부드러운 털을 지닌 동물.', length: 2, firstChar: '토', lastChar: '끼', origin: '고유어', source: 'LEXICON' },
  { word: '투구', pos: '명사', meaning: '싸움터에서 머리를 보호하기 위하여 쇠나 가죽으로 만든 모자.', length: 2, firstChar: '투', lastChar: '구', origin: '한자어', isAttack: true, source: 'LEXICON' },
  { word: '파인애플', pos: '명사', meaning: '파인애플과의 열대 식물 및 그 상큼한 과육의 열매.', length: 4, firstChar: '파', lastChar: '플', origin: '외래어', source: 'LEXICON' },
  { word: '표범', pos: '명사', meaning: '고양잇과의 식육목 포유류로 몸에 표범무늬가 있는 맹수.', length: 2, firstChar: '표', lastChar: '범', origin: '한자어', source: 'LEXICON' },
  { word: '피아노', pos: '명사', meaning: '건반을 누르면 해머가 현을 때려 소리를 내는 건반 악기.', length: 3, firstChar: '피', lastChar: '노', origin: '외래어', source: 'LEXICON' },
  { word: '하늘', pos: '명사', meaning: '지표면 위로 펼쳐진 무한한 공간.', length: 2, firstChar: '하', lastChar: '늘', origin: '고유어', source: 'LEXICON' },
  { word: '학교', pos: '명사', meaning: '일정한 목적·시설에 따라 학생을 교육하는 기관.', length: 2, firstChar: '학', lastChar: '교', origin: '한자어', source: 'LEXICON' },
  { word: '학생', pos: '명사', meaning: '학교에서 배움을 받는 사람.', length: 2, firstChar: '학', lastChar: '생', origin: '한자어', source: 'LEXICON' },
  { word: '해바라기', pos: '명사', meaning: '국화과의 한해살이풀로 노란 큰 꽃이 해를 향해 피는 식물.', length: 4, firstChar: '해', lastChar: '기', origin: '고유어', source: 'LEXICON' },
  { word: '호랑이', pos: '명사', meaning: '고양잇과의 식육목 맹수.', length: 3, firstChar: '호', lastChar: '이', origin: '고유어', source: 'LEXICON' },
  { word: '화분', pos: '명사', meaning: '식물을 심어 가꾸는 그릇.', length: 2, firstChar: '화', lastChar: '분', origin: '한자어', source: 'LEXICON' },
];
